//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funcionarios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P2Entities : DbContext
    {
        public P2Entities()
            : base("name=P2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Atividade> Atividade { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<funcionario> funcionario { get; set; }
        public DbSet<Setor> Setor { get; set; }
    }
}
