//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funcionarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class funcionario
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string endereco { get; set; }
        public int idade { get; set; }
        public int Empresa_id { get; set; }
        public int AtividadeId { get; set; }
        public int Setor_id { get; set; }
    
        public virtual Atividade Atividade { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Setor Setor { get; set; }
    }
}
